INCORRECT_PARAMETERS = b'400_INCORRECT_PARAMETERS'
NOT_FOUND = b'404_NOT_FOUND'
ALREADY_DONE = b'208_DRIVER_ALREADY_LOADED'
DRIVER_NOT_LOADED = b'406_DRIVER_NOT_LOADED'
DONE = b'200_DONE'
UNAUTHORIZED = b'401_UNAUTHORIZED'
LINKS_WITH_CYCLE = b'409_LINKS_WITH_CYCLE'


LOAD_VERB = b'load'
UNLOAD_VERB = b'unload'
