INCORRECT_PARAMETERS = '400_INCORRECT_PARAMETERS'
NOT_FOUND = '404_NOT_FOUND'
ALREADY_DONE = '208_DRIVER_ALREADY_LOADED'
DRIVER_NOT_LOADED = '406_DRIVER_NOT_LOADED'
DONE = '200_DONE'
UNAUTHORIZED = '401_UNAUTHORIZED'
LINKS_WITH_CYCLE = '409_LINKS_WITH_CYCLE'


LOAD_VERB = 'load'
UNLOAD_VERB = 'unload'
